---

- name: install epel repo
  ansible.builtin.yum:
    name: epel-release
    state: present
  when: ansible_facts.os_family == "RedHat" and ansible_facts.distribution != "Fedora"
  tags:
    - common
    - common-rhel
