---

- name: Add epel repo
  ansible.builtin.import_tasks: epel-release.yml
  when: ansible_facts.os_family == "RedHat" and ansible_facts.distribution != "Fedora"
  tags:
    - common
    - common-rhel

- name: Include os-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - defaults.yml
  tags:
    - common

- name: Install common packages|yum
  ansible.builtin.yum:
    name: "{{ common_packages }}"
    state: present
    enablerepo: epel
  when: ansible_facts.os_family == "RedHat"
  tags:
    - common

- name: Install common apps|apt
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  when: ansible_facts.os_family == "Debian"
  tags:
    - common
    - common-debian

- name: Disable firewalld service
  ansible.builtin.systemd_service:
    name: firewalld
    state: stopped
    enabled: false
  when: ansible_facts.os_family == "RedHat"
  tags:
    - common
    - common-firewalld

- name: Set selinux to permissive mode
  ansible.posix.selinux:
    policy: targeted
    state: permissive
  when: ansible_facts.os_family == "RedHat" and selinux_set_permissive
  tags:
    - common-rhel
    - common-selinux
